summmmmin/MiddleProject

- MiddleProject/.classpath
- MiddleProject/.settings/org.eclipse.jdt.core.prefs
- MiddleProject/.settings/org.eclipse.wst.common.component
- MiddleProject/.settings/org.eclipse.wst.common.project.facet.core.xml
- MiddleProject/src/main/webapp/cart.html
- MiddleProject/src/main/webapp/contact.html
- MiddleProject/src/main/webapp/css/bootstrap.min.css
> 회원가입 폼, 관심목록 페이지 html 수정

- MiddleProject/src/main/java/com/yedam/common/FrontController.java
- MiddleProject/src/main/java/com/yedam/users/controll/LoginControl.java
- MiddleProject/src/main/java/com/yedam/users/controll/LoginFormControl.java
- MiddleProject/src/main/java/com/yedam/users/controll/LogoutControl.java
- MiddleProject/src/main/java/com/yedam/users/controll/ModifyMemberControl.java
- MiddleProject/src/main/java/com/yedam/users/domain/UsersVO.java
- MiddleProject/src/main/java/com/yedam/users/mapper/UsersMapper.java
- MiddleProject/src/main/java/com/yedam/users/mapper/UsersMapper.xml
- MiddleProject/src/main/java/com/yedam/users/service/UsersService.java
- MiddleProject/src/main/java/com/yedam/users/service/UsersServiceImpl.java
- MiddleProject/src/main/java/com/yedam/wish/domain/wishVO.java
control, mapper, service, domain 기본적인 java파일 추가
> user, wish 추가

- MiddleProject/src/main/webapp/WEB-INF/views/user/signUp.jsp
> 회원가입 전화번호 13자제한 + 비밀번호 경고문구 출력

- MiddleProject/src/main/java/com/yedam/common/mybatis-config.xml
- MiddleProject/src/main/java/com/yedam/user/control/LoginControl.java
- MiddleProject/src/main/java/com/yedam/user/control/LoginFormControl.java
- MiddleProject/src/main/java/com/yedam/user/control/ModifyUserControl.java
- MiddleProject/src/main/java/com/yedam/user/service/UserService.java
- MiddleProject/src/main/java/com/yedam/user/service/UserServiceImpl.java
- MiddleProject/src/main/webapp/WEB-INF/views/user/loginForm.jsp
> login control 수정

- MiddleProject/src/main/java/com/yedam/user/control/LoginControl.java
- MiddleProject/src/main/java/com/yedam/user/mapper/UserMapper.xml
- MiddleProject/src/main/webapp/WEB-INF/views/user/loginForm.jsp
> 로그인이 가능해졌어요

- MiddleProject/src/main/java/com/yedam/common/FrontController.java
> sellGet.do 추가

- MiddleProject/src/main/java/com/yedam/sell/control/SellGetControl.java
> SellGetControl

- MiddleProject/src/main/java/com/yedam/common/FrontController.java
- MiddleProject/src/main/java/com/yedam/user/control/SignUpControl.java
- MiddleProject/src/main/java/com/yedam/user/control/SignUpFormControl.java
- MiddleProject/src/main/java/com/yedam/user/mapper/UserMapper.java
- MiddleProject/src/main/java/com/yedam/user/mapper/UserMapper.xml
- MiddleProject/src/main/java/com/yedam/user/service/UserService.java
- MiddleProject/src/main/java/com/yedam/user/service/UserServiceImpl.java
- MiddleProject/src/main/webapp/WEB-INF/views/user/loginForm.jsp
- MiddleProject/src/main/webapp/WEB-INF/views/user/signUpForm.jsp
> 회원가입 구현(90%)

- MiddleProject/src/main/java/com/yedam/user/control/LoginControl.java
> 세션에 userinfo 저장

- MiddleProject/src/main/java/com/yedam/user/control/CheckEmailControl.java
- MiddleProject/src/main/java/com/yedam/user/mapper/UserMapper.java
- MiddleProject/src/main/java/com/yedam/user/mapper/UserMapper.xml
- MiddleProject/src/main/java/com/yedam/user/service/UserService.java
- MiddleProject/src/main/java/com/yedam/user/service/UserServiceImpl.java
- MiddleProject/src/main/webapp/WEB-INF/layout/header.jsp
- MiddleProject/src/main/webapp/WEB-INF/views/user/signUpForm.jsp
- MiddleProject/src/main/webapp/js/custom.js
> 비밀번호 정규식추가

- MiddleProject/src/main/java/com/yedam/common/FrontController.java
- MiddleProject/src/main/java/com/yedam/note/control/GetNoteControl.java
- MiddleProject/src/main/java/com/yedam/note/control/NoteListControl.java
- MiddleProject/src/main/java/com/yedam/note/control/NoteSendControl.java
- MiddleProject/src/main/java/com/yedam/note/domain/noteVO.java
- MiddleProject/src/main/java/com/yedam/note/mapper/NoteMapper.java
- MiddleProject/src/main/java/com/yedam/note/mapper/NoteMapper.xml
- MiddleProject/src/main/java/com/yedam/note/service/NoteService.java
- MiddleProject/src/main/java/com/yedam/note/service/NoteServiceImpl.java
- MiddleProject/src/main/java/com/yedam/qna/control/AddQCControl.java
- MiddleProject/src/main/java/com/yedam/qna/control/ModifyQCControl.java
- MiddleProject/src/main/webapp/WEB-INF/views/note/noteSend.jsp
- MiddleProject/src/main/webapp/WEB-INF/views/qna/getQna.jsp
> 0508/04:02

- MiddleProject/src/main/java/com/yedam/common/FrontController.java
- MiddleProject/src/main/java/com/yedam/user/control/DeleteUserControl.java
- MiddleProject/src/main/java/com/yedam/user/control/LoginControl.java
- MiddleProject/src/main/java/com/yedam/user/control/ModifyUser.java
- MiddleProject/src/main/java/com/yedam/user/control/SignUpControl.java
- MiddleProject/src/main/java/com/yedam/user/domain/UserVO.java
- MiddleProject/src/main/java/com/yedam/user/mapper/UserMapper.xml
- MiddleProject/src/main/java/com/yedam/user/service/UserService.java
- MiddleProject/src/main/webapp/WEB-INF/views/user/modifyUserForm.jsp
- MiddleProject/src/main/webapp/WEB-INF/views/user/mypageView.jsp
> 회원정보 수정페이지

- MiddleProject/src/main/java/com/yedam/note/control/NoteListControl.java
- MiddleProject/src/main/java/com/yedam/note/mapper/NoteMapper.java
- MiddleProject/src/main/java/com/yedam/note/mapper/NoteMapper.xml
- MiddleProject/src/main/java/com/yedam/note/service/NoteService.java
- MiddleProject/src/main/java/com/yedam/note/service/NoteServiceImpl.java
- MiddleProject/src/main/java/com/yedam/qna/mapper/QCommentMapper.xml
- MiddleProject/src/main/java/com/yedam/qna/mapper/QnaMapper.xml
> 0508/11:47

- MiddleProject/src/main/java/com/yedam/product/control/ProdListControl.java
- MiddleProject/src/main/webapp/WEB-INF/views/product/prodList.jsp
> 0509 00:56

- MiddleProject/src/main/webapp/WEB-INF/views/product/prodList.jsp
> 0509 11:54

- MiddleProject/src/main/java/com/yedam/user/control/DeleteUserControl.java
- MiddleProject/src/main/java/com/yedam/user/control/DeleteUserFormControl.java
- MiddleProject/src/main/java/com/yedam/user/control/MypageControl.java
- MiddleProject/src/main/webapp/WEB-INF/views/user/deleteUser.jsp
- MiddleProject/src/main/webapp/WEB-INF/views/user/deleteUserForm.jsp
- MiddleProject/src/main/webapp/WEB-INF/views/user/mypagePw.jsp
- MiddleProject/src/main/webapp/js/custom.js
> 회원탈퇴 비밀번호 검증 매칭수정

- MiddleProject/src/main/webapp/WEB-INF/views/user/deleteUserForm.jsp
- MiddleProject/src/main/webapp/WEB-INF/views/user/mypagePw.jsp
- MiddleProject/src/main/webapp/WEB-INF/views/user/signUpForm.jsp
- MiddleProject/src/main/webapp/js/custom.js
> 회원가입폼 빈칸 테두리 강조

- MiddleProject/src/main/webapp/WEB-INF/views/product/prodList.jsp
> 0510 03:54

- MiddleProject/src/main/webapp/WEB-INF/layout/header.jsp
> 헤더 href 변경

- MiddleProject/src/main/java/com/yedam/user/control/LoginControl.java
- MiddleProject/src/main/webapp/WEB-INF/views/user/loginForm.jsp
- MiddleProject/src/main/webapp/WEB-INF/views/user/signUpForm.jsp
- MiddleProject/src/main/webapp/js/login.js
이메일인증 / 카카오는 진짜 여유있으면 수정하고 여유 없으면 없는기능
> 진짜마지막최종리얼끝 회원

- MiddleProject/src/main/webapp/WEB-INF/layout/header.jsp
- MiddleProject/src/main/webapp/WEB-INF/views/wish/wishList.jsp
> 헤더에 wishList추가

- MiddleProject/src/main/java/com/yedam/common/FrontController.java
- MiddleProject/src/main/java/com/yedam/wish/controll/wishListControl.java
- MiddleProject/src/main/webapp/WEB-INF/views/wish/wishList.jsp
frontcontrol에 wishlist 추가
jsp 추가
> frontcontrol에 wishlist 추가

- MiddleProject/.settings/org.eclipse.wst.common.component
- MiddleProject/src/main/java/com/yedam/common/mybatis-config.xml
- MiddleProject/src/main/java/com/yedam/wish/controll/wishListControl.java
- MiddleProject/src/main/java/com/yedam/wish/domain/WishVO.java
- MiddleProject/src/main/java/com/yedam/wish/domain/wishVO.java
- MiddleProject/src/main/java/com/yedam/wish/mapper/WishMapper.java
- MiddleProject/src/main/java/com/yedam/wish/mapper/WishMapper.xml
- MiddleProject/src/main/java/com/yedam/wish/service/WishService.java
- MiddleProject/src/main/java/com/yedam/wish/service/WishServiceImpl.java
- MiddleProject/src/main/webapp/WEB-INF/views/user/deleteUserForm.jsp
> wishlist MVC 생성

- MiddleProject/.settings/org.eclipse.wst.common.component
- MiddleProject/src/main/java/com/yedam/common/FrontController.java
- MiddleProject/src/main/java/com/yedam/user/control/ModifyUserControl.java
- MiddleProject/src/main/java/com/yedam/wish/control/AddwishList.java
- MiddleProject/src/main/java/com/yedam/wish/control/DeletewishList.java
- MiddleProject/src/main/java/com/yedam/wish/control/WishListControl.java
- MiddleProject/src/main/java/com/yedam/wish/control/wishListDelete.java
- MiddleProject/src/main/java/com/yedam/wish/domain/WishVO.java
- MiddleProject/src/main/java/com/yedam/wish/mapper/WishMapper.java
- MiddleProject/src/main/java/com/yedam/wish/mapper/WishMapper.xml
- MiddleProject/src/main/java/com/yedam/wish/service/WishService.java
- MiddleProject/src/main/java/com/yedam/wish/service/WishServiceImpl.java
- MiddleProject/src/main/webapp/WEB-INF/views/product/prodGet.jsp
- MiddleProject/src/main/webapp/WEB-INF/views/wish/wishList.jsp
- MiddleProject/src/main/webapp/js/AddWishList.js
- MiddleProject/src/main/webapp/js/wishListDelete.js
> wishlist 상품추가 가능

- MiddleProject/src/main/java/com/yedam/wish/control/DeletewishList.java
- MiddleProject/src/main/webapp/WEB-INF/views/wish/wishList.jsp
- MiddleProject/src/main/webapp/js/DeleteWishList.js
> wishlist에서 상품페이지 연결

- MiddleProject/src/main/java/com/yedam/user/control/SignUpControl.java
- MiddleProject/src/main/webapp/WEB-INF/views/user/signUpForm.jsp
- MiddleProject/src/main/webapp/js/buyDetail.js
> 회원가입폼 아이디 중복체크

- MiddleProject/src/main/webapp/WEB-INF/views/product/prodGet.jsp
- MiddleProject/src/main/webapp/WEB-INF/views/product/prodList.jsp
> 0516 00:44

- MiddleProject/src/main/java/com/yedam/user/control/ModifyUserControl.java
- MiddleProject/src/main/java/com/yedam/user/mapper/UserMapper.xml
- MiddleProject/src/main/webapp/WEB-INF/views/user/modifyUserForm.jsp
- MiddleProject/src/main/webapp/WEB-INF/views/user/mypageView.jsp
- MiddleProject/src/main/webapp/WEB-INF/views/wish/wishList.jsp
- MiddleProject/src/main/webapp/js/modifyuser.js
> 회원정보 수정 폼 유효성 검사 수정

- MiddleProject/src/main/webapp/WEB-INF/layout/header.jsp
- MiddleProject/src/main/webapp/WEB-INF/layout/template.jsp
- MiddleProject/src/main/webapp/WEB-INF/views/user/accessDenied.jsp
> 사이트 이름 변경 OWNULL
